[CO2]
description = "Carbon dioxide (CO₂) concentration"
type = "float"
range = "Depends on the subject"
created_on = "geolocate.ipynb"
source = "ANTHEM project"
source_url = "undisclosed"

[P]
description = "Atmospheric pressure data"
type = "float"
range = "Depends on the subject"
created_on = "geolocate.ipynb"
source = "ANTHEM project"
source_url = "undisclosed"

[PM1]
description = "Particulate matter (PM) concentration for particles ≤1µm"
type = "float"
range = "Depends on the subject"
created_on = "geolocate.ipynb"
source = "ANTHEM project"
source_url = "undisclosed"

[PM10]
description = "Particulate matter (PM) concentration for particles ≤10µm"
type = "float"
range = "Depends on the subject"
created_on = "geolocate.ipynb"
source = "ANTHEM project"
source_url = "undisclosed"

[PM25]
description = "Particulate matter (PM) concentration for particles ≤2.5µm"
type = "float"
range = "Depends on the subject"
created_on = "geolocate.ipynb"
source = "ANTHEM project"
source_url = "undisclosed"

[RH]
description = "Relative humidity data"
type = "float"
range = "Depends on the subject"
created_on = "geolocate.ipynb"
source = "ANTHEM project"
source_url = "undisclosed"

[T]
description = "Temperature data"
type = "float"
range = "Depends on the subject"
created_on = "geolocate.ipynb"
source = "ANTHEM project"
source_url = "undisclosed"

[VOC]
description = "Volatile organic compounds (VOCs) concentration"
type = "float"
range = "Depends on the subject"
created_on = "geolocate.ipynb"
source = "ANTHEM project"
source_url = "undisclosed"

[signal]
description = "Signal marker of change in location"
type = "int"
range = [ 0, 10000,]
created_on = "geolocate.ipynb"
source = "ANTHEM project"
source_url = "undisclosed"

[location]
description = "Location of the sample point"
type = "str"
range = [ "A", "AB", "B", "BC", "C", "CD", "D", "DE", "E", "EF", "F", "FG", "G", "GH",]
created_on = "geolocate.ipynb"
source = "ANTHEM project"
source_url = "undisclosed"

[regime]
description = "Regime of the sample point (static/dynamic) indicating if the subject is stationary or moving"
type = "str"
range = [ "dynamic", "static",]
created_on = "geolocate.ipynb"
source = "ANTHEM project"
source_url = "undisclosed"

[x]
description = "X coordinate of the sample point"
type = "float"
range = [ 9.226580468713795, 9.23668,]
created_on = "geolocate.ipynb"
source = "ANTHEM project"
source_url = "undisclosed"

[y]
description = "Y coordinate of the sample point"
type = "float"
range = [ 45.48497996269657, 45.4722252,]
created_on = "geolocate.ipynb"
source = "ANTHEM project"
source_url = "undisclosed"

[inside_green]
description = "'Dummy' variable indicating wheter the point is inside a green area or not"
type = "boolean"
range = [ 0, 1,]
created_on = "osmnx_parks.ipynb"
source = "OSM"
source_url = "https://www.openstreetmap.org/"

[close2park_25]
description = "'Dummy' variable indicating wheter the point is less than 25m away from a park or not"
type = "boolean"
range = [ 0, 1,]
created_on = "osmnx_parks.ipynb"
source = "OSM"
source_url = "https://www.openstreetmap.org/"

[close2garden_25]
description = "'Dummy' variable indicating wheter the point is less than 25m away from a garden or not"
type = "boolean"
range = [ 0, 1,]
created_on = "osmnx_parks.ipynb"
source = "OSM"
source_url = "https://www.openstreetmap.org/"

[num_green_200]
description = "Number of green areas within 200m from the point"
type = "integer"
range = [ 0, 8,]
created_on = "osmnx_parks.ipynb"
source = "OSM"
source_url = "https://www.openstreetmap.org/"

[num_green_500]
description = "Number of green areas within 500m from the point"
type = "integer"
range = [ 4, 14,]
created_on = "osmnx_parks.ipynb"
source = "OSM"
source_url = "https://www.openstreetmap.org/"

[num_green_1000]
description = "Number of green areas within 1000m from the point"
type = "integer"
range = [ 32, 10,]
created_on = "osmnx_parks.ipynb"
source = "OSM"
source_url = "https://www.openstreetmap.org/"

[proportion_green_50]
description = "Proportion of green land area within a 50m radius circle around the point"
type = "float"
range = [ 0.0, 0.373467498273193,]
created_on = "osmnx_parks.ipynb"
source = "OSM"
source_url = "https://www.openstreetmap.org/"

[proportion_green_100]
description = "Proportion of green land area within a 100m radius circle around the point"
type = "float"
range = [ 0.0, 0.4003214374464804,]
created_on = "osmnx_parks.ipynb"
source = "OSM"
source_url = "https://www.openstreetmap.org/"

[proportion_green_500]
description = "Proportion of green land area within a 500m radius circle around the point"
type = "float"
range = [ 0.12882339259190778, 0.007049415111455461,]
created_on = "osmnx_parks.ipynb"
source = "OSM"
source_url = "https://www.openstreetmap.org/"

[close2water_25]
description = "'Dummy' variable indicating wheter the point is less than 25m away from a water body"
type = "integer"
range = [ 0, 1,]
created_on = "osmnx_water.ipynb"
source = "OSM"
source_url = "https://www.openstreetmap.org/"

[close2water_100]
description = "'Dummy' variable indicating wheter the point is less than 100m away from a water body"
type = "integer"
range = [ 0, 1,]
created_on = "osmnx_water.ipynb"
source = "OSM"
source_url = "https://www.openstreetmap.org/"

[close2industry_400]
description = "'Dummy' variable indicating wheter the point is less than 400m away from an industrial area"
type = "integer"
range = [ 0, 1,]
created_on = "osmnx_landuse.ipynb"
source = "OSM"
source_url = "https://www.openstreetmap.org/"

[close2residential_10]
description = "'Dummy' variable indicating wheter the point is less than 10m away from a residential area"
type = "integer"
range = [ 0,]
created_on = "osmnx_landuse.ipynb"
source = "OSM"
source_url = "https://www.openstreetmap.org/"

[proportion_residential_400]
description = "Proportion of residential land area within a 400m radius circle around the point"
type = "float"
range = [ "np.float64(0.0)", "np.float64(0.8641728225051793)",]
created_on = "osmnx_landuse.ipynb"
source = "OSM"
source_url = "https://www.openstreetmap.org/"

[close2railway_100]
description = "'Dummy' variable indicating wheter the point is less than 100m away from a railway"
type = "integer"
range = [ 0, 1,]
created_on = "osmnx_landuse.ipynb"
source = "OSM"
source_url = "https://www.openstreetmap.org/"

[close2grass_15]
description = "'Dummy' variable indicating wheter the point is less than 15m away from a grass area"
type = "integer"
range = [ 0, 1,]
created_on = "osmnx_landuse.ipynb"
source = "OSM"
source_url = "https://www.openstreetmap.org/"

[close2grass_100]
description = "'Dummy' variable indicating wheter the point is less than 100m away from a grass area"
type = "integer"
range = [ 0, 1,]
created_on = "osmnx_landuse.ipynb"
source = "OSM"
source_url = "https://www.openstreetmap.org/"

[close2construction_50]
description = "'Dummy' variable indicating wheter the point is less than 50m away from a construction area"
type = "integer"
range = [ 0, 1,]
created_on = "osmnx_landuse.ipynb"
source = "OSM"
source_url = "https://www.openstreetmap.org/"
